---
title: "A wizard lives here."
date: 2022-02-22
---

theme: minima

title: A wizard lives here.
author: jaylingenf
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Where magic meets machine.

# social links
github_username:  jaylingenf # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
